### ISSUE TITLE
`fill.left` option?

### ISSUE THREAD

**Issue by kylebutts** [lrberge/stringmagic#3]
Hi Laurent, 

I was trying to do `fill.left` which results in an error. I know (now) that the default of `fill` is to left-fill, but it might be nice to allow it as an option so that it does not error. I think adding `"left"` here resolves this
 https://github.com/lrberge/stringmagic/blob/be80b4d12689e2d7b175264f2e7d665132e172de/R/string_magic_main.R#L2200

Similarly here (for `format`) https://github.com/lrberge/stringmagic/blob/be80b4d12689e2d7b175264f2e7d665132e172de/R/string_magic_main.R#L1654 and here (for `paste`/`append`/`insert`)
https://github.com/lrberge/stringmagic/blob/be80b4d12689e2d7b175264f2e7d665132e172de/R/string_magic_main.R#L2067

**Comment by lrberge** [comment]
Thanks Kyle for the comment: I 100% agree! Now fixed.
